---
title: "Kaggle Code"
author: "Benjamin Gerber"
date: "3/22/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup

```{r}
library(readr)
carsTrain <- read_csv("~/Desktop/Stats 101A/carsTrain.csv")
carsTestNoY <- read_csv("~/Desktop/Stats 101A/carsTestNoY.csv")
library(ggplot2)
library(car)
library(MASS)
library(corrplot)
library(gridExtra)
```



```{r}
corr<- round(cor(cbind(carsTrain$PriceNew,carsTrain$Weight,carsTrain$Width,carsTrain$Length,carsTrain$Horsepower,carsTrain$Rear.seat.room)),3)
corr
corrplot.mixed(corr, lower="number",upper="pie")
```

```{r}
ggplot(carsTrain,aes(Weight,PriceNew)) +geom_point() +geom_smooth(method="lm")
ggplot(carsTrain,aes(Width,PriceNew)) +geom_point() +geom_smooth(method="lm")
ggplot(carsTrain,aes(Length,PriceNew)) +geom_point() +geom_smooth(method="lm")
ggplot(carsTrain,aes(Horsepower,PriceNew)) +geom_point() +geom_smooth(method="lm")
ggplot(carsTrain,aes(Rear.seat.room,PriceNew)) +geom_point() +geom_smooth(method="lm")
```

```{r}
m1 <- lm(PriceNew ~ Width + Weight + Horsepower + Cylinders, data=carsTrain)
summary(m1)
```

```{r}
m2 <- lm(PriceNew ~ Width + Weight + Horsepower + AirBags, data=carsTrain)
summary(m2)
```

```{r}
diagPlot<-function(model){
  p1<-ggplot(model, aes(model$fitted, model$residuals),label=rownames(bonds))+geom_point()
  p1<-p1+stat_smooth(method="loess")+geom_hline(yintercept=0, col="red", linetype="dashed")
  p1<-p1+xlab("Fitted values")+ylab("Residuals") 
  p1<-p1+ggtitle("Residual vs Fitted Plot")+theme_bw()
  
  p2<-ggplot(model,aes(sample=rstandard(model))) + stat_qq() + stat_qq_line()
  p2<-p2+xlab("Theoretical Quantiles")+ylab("Standardized Residuals") 
  p2<-p2+ggtitle("Normal Q-Q")

  p3<-ggplot(model, aes(model$fitted, sqrt(abs(rstandard(model)))))+geom_point(na.rm=TRUE)
  p3<-p3+stat_smooth(method="loess", na.rm = TRUE)+xlab("Fitted Value")
  p3<-p3+ylab(expression(sqrt("|Standardized residuals|")))
  p3<-p3+ggtitle("Scale-Location")+theme_bw()+geom_hline(yintercept=sqrt(2), col="red", linetype="dashed")
  
  p4<-ggplot(model, aes(seq_along(cooks.distance(model)), cooks.distance(model)))+geom_bar(stat="identity", position="identity")
  p4<-p4+xlab("Obs. Number")+ylab("Cook's distance")
  p4<-p4+ggtitle("Cook's distance")+theme_bw()+geom_hline(yintercept=4/(length(model$residuals-2)), col="red", linetype="dashed")
  
  p5<-ggplot(model, aes(hatvalues(model), rstandard(model)))+geom_point(aes(size=cooks.distance(model)), na.rm=TRUE)
  p5<-p5+stat_smooth(method="loess", na.rm=TRUE) 
  p5<-p5+xlab("Leverage")+ylab("Standardized Residuals") 
  p5<-p5+ggtitle("Residual vs Leverage Plot") 
  p5<-p5+scale_size_continuous("Cook's Distance", range=c(1,5))
  p5<-p5+theme_bw()+theme(legend.position="bottom")+geom_hline(yintercept=c(-2,2),col="red",linetype="dashed")+geom_vline(xintercept=4/(length(model$residuals)),col="blue",linetype="dashed")+ylim(-4,4)
  
  p6<-ggplot(model, aes(hatvalues(model), cooks.distance(model)))+geom_point( na.rm=TRUE)+stat_smooth(method="loess", na.rm=TRUE)
  p6<-p6+xlab("Leverage hii")+ylab("Cook's Distance")
  p6<-p6+ggtitle("Cook's dist vs Leverage") 
  p6<-p6+geom_abline(slope=seq(0,3,0.5), color="gray", linetype="dashed") 
  p6<-p6+theme_bw()
  return(grid.arrange(p1,p2,p3,p4,p5,p6,ncol=3))
}
```

```{r}
diagPlot(m2)
```

```{r}
vif(m2)
```

```{r}
m3 <- lm(PriceNew ~ Width + Horsepower + AirBags, data=carsTrain)
anova(m3,m2)
```

```{r}
summary(powerTransform(cbind(PriceNew,Width,Weight,Horsepower)~1,data=carsTrain))
```

```{r}
final <- lm(((PriceNew^-0.5)) ~ I(Width^-1) + +I(Weight^1/3) + I(Horsepower^-1/3) +AirBags, data=carsTrain)
summary(final)
```

```{r error=TRUE}
mmps(final)
```

```{r}
leveragePlots(final)
```

```{r}
par(mfrow = c(2,2))
plot(final)
```

```{r}
extractAIC(final,k=log(1500))
```

```{r}
PriceNew <- I(predict(final,carsTestNoY)^-2)
Ob <- 1:500
KaggleProj <- data.frame(Ob,PriceNew)
write.csv(KaggleProj,file="FINAL2.csv", row.names= FALSE)
```
```









